# This file contains values from Cookiecutter

default_context:
  project_name: "python-hooks"
  project_description: "A React inspired way to code in Python"
  organization: "Amit Assaraf"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "amitassaraf"
  email: "amit.assaraf@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
